### ISSUE TITLE
설치 환경에 대한 질문입니다.

### ISSUE THREAD

**Issue by LenKIM** [kakao-arena/shopping-classification#2]
주어진 환경에 맞쳐 데이터를 수집하기 위한 시도 중, 제가 사용하고 있는 PC의 경우 Windows를 활용하고 있습니다.

Python2 와 Tensorflow를 원도우에서 쓰기위해서는 python3로 업데이트하는 할 수 밖에 없는데, 그렇게 되면 cPickle 모듈이 동작하지 않아 data.py를 실행시킬 수 없습니다. 

https://stackoverflow.com/questions/45316569/how-to-install-tensorflow-on-python-2-7-on-windows

해당 이슈를 보고 파악했습니다만, 혹시 제가 잘못알고 있는 부분이 있는지 확인부탁드립니다.

혹시 범용성을 위해 base_code를 수정할 수는 없는지 이슈남깁니다.

**Comment by ummae** [comment]
@LenKIM 
아마 쓰고 계신 파이썬3 버전에서는 cPickle 대신 pickle을 사용해야할 겁니다. cPickle부분을 pickle로 바꾸고 loads, dumps 메소드도 조금씩 수정해야할텐데요. 이밖에도 문자열 관련 이슈(byte, str, unicode)등 파이썬3로 바꾸게 되면 수정할 것들이 있을 듯 합니다.

베이스 솔루션은 참고용으로 제공한 것이라 파이썬 버전별로 제공할 생각까지는 못했습니다. 재현을 해보는 것이 목적이라면 VirtualBox와 같이 가상환경의 비-윈도우에서 테스트하시는 것이 나을 것 같습니다. 베이스 솔루션을 파이썬3로 포팅해서 공유하는 것도 검토해보겠지만, 확답을 드리기 어려울 것 같습니다. 진행하더라도 정확히 언제까지 제공드린다고 말씀드리기도 어려울 것 같네요. 양해부탁드릴께요.

**Comment by LenKIM** [comment]
해당 이슈에 대한 답변을 들었기 때문에 Close하겠습니다.
감사합니다.
