### ISSUE TITLE
data.py 실행 관련 오류 확인 부탁드립니다.

### ISSUE THREAD

**Issue by jaekyu-sim** [kakao-arena/shopping-classification#5]
https://github.com/kakao-arena/shopping-classification/blob/8e6c97514a3cbe63c7ff7d8ab1e01e43a9b8ef8c/data.py#L177

Line 177 실행시 name 'data' is not defined 라는 에러가 발생합니다.

실제 소스코드 확인시 data 라는 변수가 어떻게 정의되어있는지 나와잇지 않은것으로 보이는데, 소스코드 실행해보신 분들은 어떻게 진행 하셨었나요?

**Comment by ummae** [comment]
@Jaekyu-Sim 파싱이 되지 않는 데이터를 거르는 부분인데 `data`가 아니라 `y`를 참조하는 게 맞을 것 같습니다. 확인 해봐야겠지만 아마 `__main__`의 `data`가 참조가 되는 게 아닌가 싶습니다. 마스터 브랜치에 코드 수정해뒀습니다.

**Comment by h4wldev** [comment]
@Jaekyu-Sim 문제가 해결된 것 같아 이슈 닫겠습니다.
